version: '3'
services:
  remote-unit-client:
    build: .
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    volumes:
      - ./config.json:/app/config.json
      - ./cache:/app/cache
    environment:
      - PYTHONUNBUFFERED=1
