version: '3'
services:
  remote-unit-client:
    container_name: lohp-client
    build: .
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    volumes:
      - ./:/app
      - ./cache:/app/cache
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
