version: '3'
services:
  escape-room-control:
    build: .
    ports:
      - "5000:5000"
      - "8765:8765"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/snd:/dev/snd"
    privileged: true
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
