"""Server -> ESP32-node audio downlink over the ESPHome native API.

Per-room audio on the node boxes (wiring-guides/room-node-audio-plan.md):
short effect cues are compiled into each node's firmware (fired via the
node's `play_cue` api action, ~100-300ms to sound) and background music
streams from this server's existing GET /api/audio/<file> endpoint through
the node's media_player. Cue firmware assets are generated by
sim/esphome/make_node_audio.py from the same node_audio_config.json.

This path is ADDITIVE beside the WebSocket unit path: RemoteHostManager still
emits every WS message (the sim's browser audio client depends on them);
rooms listed in node_audio_config.json also get the node dispatch. Dispatch
is fire-and-forget behind a per-node FIFO lock — a dead node never delays an
effect's lights, and commands to one node can't reorder (same ordering
discipline the WS client path got in the 2026-07 concurrency hardening).

Per-effect volume is BAKED into the generated cue files, so a runtime
audio_params volume override (no effect uses one today) is ignored here.
"""
import asyncio
import json
import logging
import os
import re
import time
from urllib.parse import quote

logger = logging.getLogger(__name__)

try:
    from aioesphomeapi import APIClient, MediaPlayerCommand
    AIOESPHOMEAPI_AVAILABLE = True
except ImportError:
    AIOESPHOMEAPI_AVAILABLE = False

CONNECT_TIMEOUT = 5   # seconds; only the first command after a (re)connect pays it
CONNECT_BACKOFF = 5   # after a failed connect, fail further commands fast this long
STALE_AFTER = 5       # a command that waited this long behind the node lock is
                      # dropped — a thunder cue arriving after a reconnect backlog
                      # would fire long after its lightning


class _BackingOff(Exception):
    """Connect skipped because the last attempt just failed (quiet fast-fail)."""


def cue_id(audio_file):
    """Firmware cue id for an audio filename ("monkey-shrine-complete.mp3" ->
    "monkey_shrine_complete"). make_node_audio.py imports this so the ids the
    server sends always match the ids compiled into the firmware."""
    stem = os.path.splitext(os.path.basename(audio_file))[0]
    return re.sub(r'[^a-z0-9]+', '_', stem.lower()).strip('_')


class _NodeConn:
    """One room node: lazy connection + per-node FIFO command lock."""

    def __init__(self, room, host, port):
        self.room = room
        self.host = host
        self.port = port
        self.lock = asyncio.Lock()
        self.client = None
        self.media_key = None
        self.services = {}
        self._fail_ts = 0.0

    async def _ensure_connected(self):
        if self.client is not None:
            return
        if time.monotonic() - self._fail_ts < CONNECT_BACKOFF:
            raise _BackingOff()
        client = APIClient(self.host, self.port, password='')
        await client.connect(login=True)
        entities, services = await client.list_entities_services()
        self.media_key = next((e.key for e in entities
                               if type(e).__name__ == 'MediaPlayerInfo'), None)
        self.services = {s.name: s for s in services}
        self.client = client
        logger.info(f"Node audio connected: {self.room} @ {self.host}:{self.port}")

    async def _drop(self):
        client, self.client = self.client, None
        self.media_key = None
        self.services = {}
        if client is not None:
            try:
                await client.disconnect()
            except Exception:
                pass

    async def _run(self, what, call):
        """Run `call()` under the node lock; one reconnect-and-retry on failure.
        Commands that went stale waiting for the lock are dropped, and while a
        node is unreachable everything fails fast (CONNECT_BACKOFF) instead of
        queueing 2x CONNECT_TIMEOUT per command."""
        dispatched_at = time.monotonic()
        async with self.lock:
            if time.monotonic() - dispatched_at > STALE_AFTER:
                logger.debug(f"Node audio [{self.room}] dropped stale {what}")
                return False
            for attempt in (1, 2):
                try:
                    await asyncio.wait_for(self._ensure_connected(), CONNECT_TIMEOUT)
                    await call()
                    return True
                except _BackingOff:
                    logger.debug(f"Node audio [{self.room}] {what} skipped "
                                 "(node unreachable, backing off)")
                    return False
                except Exception as e:
                    if self.client is None:
                        # Failed while connecting (incl. wait_for timeout, whose
                        # cancellation never reaches _ensure_connected's frame):
                        # arm the fast-fail window.
                        self._fail_ts = time.monotonic()
                    await self._drop()
                    if attempt == 2:
                        logger.error(f"Node audio [{self.room}] {what} failed: "
                                     f"{type(e).__name__}: {e}")
        return False

    async def play_cue(self, cue):
        async def call():
            svc = self.services.get('play_cue')
            if svc is None:
                raise RuntimeError("node exposes no play_cue action "
                                   "(generated cues package not flashed?)")
            result = self.client.execute_service(svc, {'cue': cue})
            if asyncio.iscoroutine(result):  # awaitable in newer aioesphomeapi
                await result
        return await self._run(f"play_cue {cue}", call)

    async def play_url(self, url):
        async def call():
            if self.media_key is None:
                raise RuntimeError("node has no media_player entity")
            await self.client.media_player_command(self.media_key, media_url=url,
                                                   announcement=False)
        return await self._run(f"play {url}", call)

    async def stop(self, announcement):
        """announcement=True stops effect cues (music keeps playing, matching
        the VLC client's audio_stop); False stops the music pipeline."""
        async def call():
            if self.media_key is None:
                raise RuntimeError("node has no media_player entity")
            await self.client.media_player_command(self.media_key,
                                                   command=MediaPlayerCommand.STOP,
                                                   announcement=announcement)
        return await self._run(f"stop(announcement={announcement})", call)


class NodeAudioManager:
    def __init__(self, audio_manager=None, config_file='node_audio_config.json',
                 conn_factory=None):
        self.audio_manager = audio_manager
        self.server_host = None
        self.server_port = 5000
        self.rooms = {}          # room name (lower) -> _NodeConn
        self._tasks = set()      # keep fire-and-forget tasks referenced
        self._conn_factory = conn_factory or _NodeConn
        self._load(config_file)

    def _load(self, config_file):
        if not os.path.exists(config_file):
            logger.info(f"No {config_file} — node audio disabled")
            return
        try:
            with open(config_file) as f:
                config = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.error(f"Error loading {config_file}: {e} — node audio disabled")
            return
        rooms = config.get('rooms', {})
        if rooms and not AIOESPHOMEAPI_AVAILABLE:
            logger.error(f"{config_file} lists rooms but aioesphomeapi is not "
                         "installed — node audio disabled")
            return
        self.server_host = config.get('server_host')
        self.server_port = config.get('server_port', 5000)
        if rooms and not self.server_host:
            logger.error(f"{config_file} needs server_host (the LAN address nodes "
                         "stream /api/audio from) — node audio disabled")
            return
        for room, entry in rooms.items():
            self.rooms[room.lower()] = self._conn_factory(
                room, entry['host'], entry.get('port', 6053))
        if self.rooms:
            logger.info(f"Node audio enabled for: {sorted(c.room for c in self.rooms.values())}")

    @property
    def enabled(self):
        return bool(self.rooms)

    def enabled_for(self, room):
        return room is not None and room.lower() in self.rooms

    def music_url(self, music_file):
        return (f"http://{self.server_host}:{self.server_port}"
                f"/api/audio/{quote(music_file)}")

    def handle_command(self, room, command, data):
        """Mirror a WS audio command onto the node(s). room=None means every
        node room (matching the WS broadcast semantics). Fire-and-forget:
        returns True if it was dispatched to at least one node."""
        if room is None:
            conns = list(self.rooms.values())
        elif self.enabled_for(room):
            conns = [self.rooms[room.lower()]]
        else:
            return False
        dispatched = False
        for conn in conns:
            coro = self._command_coro(conn, command, data or {})
            if coro is not None:
                task = asyncio.create_task(coro)
                self._tasks.add(task)
                task.add_done_callback(self._tasks.discard)
                dispatched = True
        return dispatched

    def _command_coro(self, conn, command, data):
        if command == 'play_effect_audio':
            if data.get('loop'):
                logger.warning(f"Node audio [{conn.room}]: loop requested for "
                               f"{data.get('file_name')} — embedded cues don't loop")
            return conn.play_cue(cue_id(data['file_name']))
        if command == 'start_background_music':
            return conn.play_url(self.music_url(data['music_file']))
        if command == 'stop_background_music':
            return conn.stop(announcement=False)
        if command == 'audio_stop':
            return conn.stop(announcement=True)
        logger.debug(f"Node audio: no mapping for WS command '{command}'")
        return None
