"""Server -> ESP32-node audio downlink over the ESPHome native API.

Per-room audio on the node boxes (wiring-guides/room-node-audio-plan.md).
NOTHING is stored on the nodes (2026-07-25, Tim — supersedes the embedded
play_cue design): effect cues stream to the node's announcement pipeline as
GET /api/audio/cues/<cue_id>.wav URLs (volume-baked WAVs generated by
sim/esphome/make_node_audio.py), and ambience beds stream from the existing
GET /api/audio/<file> endpoint through the media pipeline.

This path is ADDITIVE beside the WebSocket unit path: RemoteHostManager still
emits every WS message (the sim's browser audio client depends on them);
rooms listed in node_audio_config.json also get the node dispatch. Dispatch
is fire-and-forget behind a per-node FIFO lock — a dead node never delays an
effect's lights, and commands to one node can't reorder (same ordering
discipline the WS client path got in the 2026-07 concurrency hardening).

The global `effect_level` (audio_config / data/audio_levels.json) is BAKED
into the generated cue WAVs (per-effect volume fields are legacy trim since
2026-08-22), so a runtime audio_params volume override is ignored here.

Cues play as ANNOUNCEMENTS over the streaming bed: since 2026-08-22 (flat
mix) the node's mixer just sums them — pre-08-22 firmware still ducks the
media pipeline 12 dB under a cue and recovers (audio_s3.yaml) — the bed is
never stopped for a cue. Because the speaker media_player has ONE entity
volume shared by both pipelines, bed gain is baked into the generated node
stream (remote_host_manager -> audio_manager.prepare_node_ambience_stream)
and the entity volume stays pinned at 1.0.
"""
import asyncio
import json
import logging
import os
import re
import time
import inspect
from urllib.parse import quote, urlencode

logger = logging.getLogger(__name__)

try:
    from aioesphomeapi import APIClient, MediaPlayerCommand
    AIOESPHOMEAPI_AVAILABLE = True
except ImportError:
    AIOESPHOMEAPI_AVAILABLE = False

CONNECT_TIMEOUT = 10  # seconds; only the first command after a (re)connect pays it
                      # (5 until 2026-08-30: playa RF runs 300-500ms RTT with
                      # loss — the tight timeout turned marginal links into
                      # constant flapping)
CONNECT_BACKOFF = 5   # after a failed connect, fail further commands fast this long
STALE_AFTER = 5       # a command that waited this long behind the node lock is
                      # dropped — a thunder cue arriving after a reconnect backlog
                      # would fire long after its lightning
KEEPALIVE_TICK_S = 10  # connection keepalive cadence (see _NodeConn._maintain)
PROBE_TIMEOUT = 8      # keepalive device_info probe (3 until 2026-08-30 — see
                       # CONNECT_TIMEOUT; a probe miss tears the connection down,
                       # so it must ride out playa RTT spikes)
# A node that stays unreachable backs its keepalive off exponentially
# (7-14-28-56s, capped here) instead of a full connect attempt every tick —
# powered-off boxes are normal at the bench and must cost ~nothing. A box
# powering back on is picked up by the next backed-off tick (<=60s) or
# instantly by any dispatched command (_run connects lazily).
KEEPALIVE_MAX_BACKOFF_S = 60
NODE_GLOBAL_MAZE_AMBIENCE = True

# aioesphomeapi MediaPlayerState values the bed watchdog cares about.
MEDIA_IDLE = 1

# A connected node whose media pipeline reports IDLE this long, while the maze
# bed should be playing, gets the bed re-dispatched (see
# reconcile_maze_ambience_on_nodes). Longer than any legitimate gap: a
# stream's fetch startup is ~1s and cue announcements report ANNOUNCING.
STALL_GRACE_S = 12.0
# ...unless the bed's window ends within this — the reconciler is about to
# rotate anyway, and a once-mode bed sits IDLE through its once_pad_s tail.
ROTATION_SLOP_S = 10.0


class _BackingOff(Exception):
    """Connect skipped because the last attempt just failed (quiet fast-fail)."""


def cue_id(audio_file):
    """Firmware cue id for an audio filename ("monkey-shrine-complete.mp3" ->
    "monkey_shrine_complete"). make_node_audio.py imports this so the ids the
    server sends always match the ids compiled into the firmware."""
    stem = os.path.splitext(os.path.basename(audio_file))[0]
    return re.sub(r'[^a-z0-9]+', '_', stem.lower()).strip('_')


class _NodeConn:
    """One room node: lazy connection + per-node FIFO command lock."""

    def __init__(self, room, host, port):
        self.room = room
        self.host = host
        self.port = port
        self.lock = asyncio.Lock()
        self.client = None
        self.media_key = None
        self._fail_ts = 0.0
        # The room's own background bed owns the media pipeline while True:
        # maze-wide ambience commands must not touch it (beds share the
        # node's single media pipeline — last command wins).
        self.bed_active = False
        # Last media_player state the node PUSHED (subscribe_states), and when
        # it changed. The bed watchdog trusts this over command results: a
        # play command can succeed while the stream later dies (server restart
        # mid-fetch, 2026-08-17) and only the device's own state shows it.
        self.media_state = None
        self.media_state_at = 0.0
        # Live entity mirror for the field-calibration tool
        # (calibration_manager.py): entity info from list_entities_services at
        # connect, latest pushed state per key from the same subscribe_states
        # the bed watchdog uses. Cleared on drop so nothing reads stale.
        self.entities = {}       # key -> {'name','object_id','type','options'}
        self.entity_states = {}  # key -> {'state', 'at'}
        self._maintain_task = None
        self._down_ticks = 0  # consecutive keepalive ticks without a connection

    async def _ensure_connected(self):
        if self.client is not None:
            return
        if time.monotonic() - self._fail_ts < CONNECT_BACKOFF:
            raise _BackingOff()
        client = APIClient(self.host, self.port, password='')
        await client.connect(login=True)
        entities, _ = await client.list_entities_services()
        self.media_key = next((e.key for e in entities
                               if type(e).__name__ == 'MediaPlayerInfo'), None)
        self.entities = {
            e.key: {'name': e.name,
                    'object_id': getattr(e, 'object_id', ''),
                    'type': type(e).__name__,
                    'options': list(getattr(e, 'options', []) or [])}
            for e in entities}
        try:
            client.subscribe_states(self._on_state)
        except Exception as e:
            logger.debug(f"Node audio [{self.room}]: state subscription "
                         f"unavailable: {e}")
        self.client = client
        logger.info(f"Node audio connected: {self.room} @ {self.host}:{self.port}")

    def _on_state(self, state):
        key = getattr(state, 'key', None)
        if key is not None:
            value = getattr(state, 'state', None)
            if getattr(state, 'missing_state', False):
                value = None
            self.entity_states[key] = {'state': value, 'at': time.time()}
        if type(state).__name__ != 'MediaPlayerEntityState':
            return
        try:
            new_state = int(state.state)
        except (TypeError, ValueError):
            return
        if new_state != self.media_state:
            # Timestamp only transitions: media_state_at means "in this state
            # since", which is what the watchdog's grace period measures.
            self.media_state = new_state
            self.media_state_at = time.monotonic()

    async def _drop(self):
        client, self.client = self.client, None
        self.media_key = None
        self.media_state = None
        self.media_state_at = 0.0
        self.entities = {}
        self.entity_states = {}
        if client is not None:
            try:
                await client.disconnect()
            except Exception:
                pass

    def ensure_maintained(self):
        """Start (idempotently) the background keepalive for this node."""
        if self._maintain_task is None or self._maintain_task.done():
            self._maintain_task = asyncio.create_task(self._maintain())
        return self._maintain_task

    async def _maintain(self):
        """Keep the native API connection up instead of connecting lazily on
        the first command. This makes liveness real — audio_rooms() and the
        ambient scatter only count rooms that can actually play — and the
        maze bed starts on a warm connection instead of racing a cold
        connect (the 2026-08-17 silent-bed failure). Down nodes stay quiet:
        one INFO per lost connection, DEBUG while retrying."""
        while True:
            try:
                async with self.lock:
                    if self.client is None:
                        try:
                            await asyncio.wait_for(self._ensure_connected(),
                                                   CONNECT_TIMEOUT)
                        except _BackingOff:
                            pass
                        except Exception as e:
                            if self.client is None:
                                self._fail_ts = time.monotonic()
                            await self._drop()
                            logger.debug(f"Node audio [{self.room}] keepalive "
                                         f"connect failed: {e}")
                    else:
                        probe = getattr(self.client, 'device_info', None)
                        if probe is not None:
                            try:
                                await asyncio.wait_for(probe(), PROBE_TIMEOUT)
                            except Exception as e:
                                await self._drop()
                                self._fail_ts = time.monotonic()
                                logger.info(f"Node audio lost: {self.room} "
                                            f"({type(e).__name__})")
            except asyncio.CancelledError:
                raise
            except Exception as e:
                logger.error(f"Node audio keepalive [{self.room}] tick failed: {e}",
                             exc_info=True)
            if self.client is None:
                self._down_ticks = min(self._down_ticks + 1, 8)
                delay = min(KEEPALIVE_MAX_BACKOFF_S,
                            KEEPALIVE_TICK_S * (2 ** (self._down_ticks - 1)))
            else:
                self._down_ticks = 0
                delay = KEEPALIVE_TICK_S
            await asyncio.sleep(delay)

    async def _run(self, what, call):
        """Run `call()` under the node lock; one reconnect-and-retry on failure.
        Commands that went stale waiting for the lock are dropped, and while a
        node is unreachable everything fails fast (CONNECT_BACKOFF) instead of
        queueing 2x CONNECT_TIMEOUT per command."""
        dispatched_at = time.monotonic()
        async with self.lock:
            if time.monotonic() - dispatched_at > STALE_AFTER:
                logger.debug(f"Node audio [{self.room}] dropped stale {what}")
                return False
            for attempt in (1, 2):
                try:
                    await asyncio.wait_for(self._ensure_connected(), CONNECT_TIMEOUT)
                    result = call()
                    if inspect.isawaitable(result):
                        await result
                    return True
                except _BackingOff:
                    logger.debug(f"Node audio [{self.room}] {what} skipped "
                                 "(node unreachable, backing off)")
                    return False
                except Exception as e:
                    if self.client is None:
                        # Failed while connecting (incl. wait_for timeout, whose
                        # cancellation never reaches _ensure_connected's frame):
                        # arm the fast-fail window.
                        self._fail_ts = time.monotonic()
                    await self._drop()
                    if attempt == 2:
                        logger.error(f"Node audio [{self.room}] {what} failed: "
                                     f"{type(e).__name__}: {e}")
        return False

    async def play_announcement(self, url, volume=None):
        """Effect cue: stream `url` through the announcement pipeline (plays over
        the active bed, which resumes when the cue ends)."""
        def call():
            if self.media_key is None:
                raise RuntimeError("node has no media_player entity")
            return self.client.media_player_command(self.media_key, media_url=url,
                                                    announcement=True,
                                                    volume=volume)
        return await self._run(f"announce {url}", call)

    async def play_url(self, url, volume=None):
        def call():
            if self.media_key is None:
                raise RuntimeError("node has no media_player entity")
            return self.client.media_player_command(self.media_key, media_url=url,
                                                    announcement=False,
                                                    volume=volume)
        return await self._run(f"play {url}", call)

    async def stop(self, announcement):
        """announcement=True stops effect cues (beds keep playing, matching
        the VLC client's audio_stop); False stops the media pipeline."""
        def call():
            if self.media_key is None:
                raise RuntimeError("node has no media_player entity")
            return self.client.media_player_command(self.media_key,
                                                    command=MediaPlayerCommand.STOP,
                                                    announcement=announcement)
        return await self._run(f"stop(announcement={announcement})", call)

    # --- calibration writes (calibration_manager.py) ---
    # Same connection + FIFO lock as audio commands, so a gate tweak can't
    # interleave with a cue dispatch mid-reconnect.

    async def set_number(self, key, value):
        """Write an ESPHome number entity (LD2410 gate limits/timeout,
        LD2450 zone coords — sim/esphome/packages/)."""
        def call():
            return self.client.number_command(key, float(value))
        return await self._run(f"set_number {key}={value}", call)

    async def set_select(self, key, option):
        """Write a select entity (LD2450 zone type)."""
        def call():
            return self.client.select_command(key, str(option))
        return await self._run(f"set_select {key}={option}", call)

    async def set_switch(self, key, on):
        """Write a switch entity (LD2450 multi-target)."""
        def call():
            return self.client.switch_command(key, bool(on))
        return await self._run(f"set_switch {key}={on}", call)


class NodeAudioManager:
    def __init__(self, audio_manager=None, config_file='node_audio_config.json',
                 conn_factory=None):
        self.audio_manager = audio_manager
        self.server_host = None
        self.server_port = 5000
        self.rooms = {}          # room name (lower) -> _NodeConn
        self.maze_ambience_file = None
        self.maze_ambience_data = None
        self._tasks = set()      # keep fire-and-forget tasks referenced
        self._repeat_tasks = {}  # _NodeConn -> bounded maze-loop repeat task
        self._conn_factory = conn_factory or _NodeConn
        self._load(config_file)

    def _load(self, config_file):
        if not os.path.exists(config_file):
            logger.info(f"No {config_file} — node audio disabled")
            return
        try:
            with open(config_file) as f:
                config = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            logger.error(f"Error loading {config_file}: {e} — node audio disabled")
            return
        rooms = config.get('rooms', {})
        if rooms and not AIOESPHOMEAPI_AVAILABLE:
            logger.error(f"{config_file} lists rooms but aioesphomeapi is not "
                         "installed — node audio disabled")
            return
        self.server_host = config.get('server_host')
        self.server_port = config.get('server_port', 5000)
        if rooms and not self.server_host:
            logger.error(f"{config_file} needs server_host (the LAN address nodes "
                         "stream /api/audio from) — node audio disabled")
            return
        for room, entry in rooms.items():
            self.rooms[room.lower()] = self._conn_factory(
                room, entry['host'], entry.get('port', 6053))
        if self.rooms:
            logger.info(f"Node audio enabled for: {sorted(c.room for c in self.rooms.values())}")

    @property
    def enabled(self):
        return bool(self.rooms)

    def enabled_for(self, room):
        return room is not None and room.lower() in self.rooms

    def enabled_rooms(self):
        """Room names with a speaker node configured, original casing."""
        return [c.room for c in self.rooms.values()]

    def ensure_running(self):
        """Start every node's connection keepalive (idempotent)."""
        for conn in self.rooms.values():
            conn.ensure_maintained()

    def is_connected(self, room):
        """Whether the room's node has a LIVE native API connection — the
        difference between 'a box is configured' and 'a speaker can play
        right now' (the ambient scatter was firing into offline boxes)."""
        conn = self.rooms.get((room or '').lower())
        return bool(conn and conn.client is not None)

    def connected_rooms(self):
        """Rooms whose node is connected right now, original casing."""
        return [c.room for c in self.rooms.values() if c.client is not None]

    def audio_url(self, audio_file, offset_s=None):
        query = ""
        if offset_s is not None:
            try:
                offset = max(0.0, float(offset_s))
            except (TypeError, ValueError):
                offset = 0.0
            if offset >= 0.25:
                query = "?" + urlencode({"offset_s": f"{offset:.3f}"})
        return (f"http://{self.server_host}:{self.server_port}"
                f"/api/audio/{quote(audio_file)}{query}")

    def cue_url(self, audio_file):
        return (f"http://{self.server_host}:{self.server_port}"
                f"/api/audio/cues/{cue_id(audio_file)}.wav")

    @staticmethod
    def _volume(data, default):
        try:
            volume = float((data or {}).get('volume', default))
        except (TypeError, ValueError):
            volume = default
        return max(0.0, min(1.0, volume))

    @classmethod
    def _bed_volume(cls, data):
        """Entity volume for a bed play. The speaker media_player has ONE
        volume shared by both pipelines (media AND announcement), so a bed
        played at 0.35 entity volume would jump to full the moment a cue
        sets 1.0. Beds whose gain was baked into the generated node stream
        (`node_gain_baked`, remote_host_manager) pin the entity at 1.0 —
        the same level every cue uses; only legacy un-baked payloads still
        ride the entity volume."""
        if (data or {}).get('node_gain_baked'):
            return 1.0
        return cls._volume(data, 0.35)

    @staticmethod
    def _node_file(data):
        return data.get('node_file_name') or data['file_name']

    @staticmethod
    def _node_loop(data):
        if 'node_loop' in data:
            return bool(data.get('node_loop'))
        return bool(data.get('loop'))

    @staticmethod
    def _node_duration(data):
        return data.get('node_duration_s') or data.get('duration_s')

    def _maze_offset_s(self, data):
        try:
            started_at = float(data.get('sync_started_at_s'))
        except (TypeError, ValueError):
            return None
        offset = max(0.0, time.monotonic() - started_at)
        try:
            duration_s = float(self._node_duration(data) or 0)
        except (TypeError, ValueError):
            duration_s = 0.0
        if duration_s > 0 and data.get('loop'):
            offset %= duration_s
        elif duration_s > 0:
            offset = min(offset, max(0.0, duration_s - 0.5))
        return offset

    def _maze_audio_url(self, data):
        return self.audio_url(self._node_file(data), offset_s=self._maze_offset_s(data))

    def handle_command(self, room, command, data):
        """Mirror a WS audio command onto the node(s). room=None means every
        node room (matching the WS broadcast semantics). Fire-and-forget:
        returns True if it was dispatched to at least one node."""
        # Track maze ambience here: room bed stops hand the freed pipeline
        # back to this file in _command_coro.
        if command == 'start_maze_ambience':
            self.maze_ambience_data = dict(data or {})
            self.maze_ambience_file = self.maze_ambience_data.get('file_name')
        elif command == 'stop_maze_ambience':
            self.maze_ambience_file = None
            self.maze_ambience_data = None
            self._cancel_repeats()
        if room is None:
            conns = list(self.rooms.values())
        elif self.enabled_for(room):
            conns = [self.rooms[room.lower()]]
        else:
            return False
        dispatched = False
        for conn in conns:
            coro = self._command_coro(conn, command, data or {})
            if coro is not None:
                task = asyncio.create_task(coro)
                self._tasks.add(task)
                task.add_done_callback(self._tasks.discard)
                dispatched = True
        # A maze ambience start/stop may be fully deferred because every node
        # currently has a room bed on its single media pipeline. The desired
        # file was still recorded above, so treat that as handled.
        if not dispatched and command in ('start_maze_ambience', 'stop_maze_ambience') and conns:
            return True
        return dispatched

    def _command_coro(self, conn, command, data):
        if command == 'play_effect_audio':
            if data.get('loop'):
                logger.warning(f"Node audio [{conn.room}]: loop requested for "
                               f"{data.get('file_name')} — embedded cues don't loop")
            # Cue WAVs are volume-baked by make_node_audio.py and play as
            # announcements: the mixer plays them over the bed and
            # recovers (audio_s3.yaml) — the media pipeline is NOT stopped, so
            # ambience keeps playing straight through a cue. volume=1.0 keeps
            # the shared entity volume pinned at the level beds are baked for.
            return conn.play_announcement(self.cue_url(data['file_name']), volume=1.0)
        if command == 'play_room_ambience':
            # A bed belongs on the media pipeline, so effect cues mix over it as
            # announcements instead of replacing it. The pipeline is single —
            # while bed_active, maze ambience commands leave it alone (the bed
            # overrides maze ambience in its room). Remaining caveat until a
            # bed-room node exists: ESPHome's media player has no repeat, so
            # the bed streams through once instead of looping.
            conn.bed_active = True
            self._cancel_repeat(conn)
            node_file = self._node_file(data)
            if self._node_loop(data):
                logger.warning(f"Node audio [{conn.room}]: ambience "
                               f"{data.get('file_name')} streams once — the node media "
                               f"player has no repeat")
            return conn.play_url(self.audio_url(node_file), volume=self._bed_volume(data))
        if command == 'stop_room_ambience':
            conn.bed_active = False
            if (NODE_GLOBAL_MAZE_AMBIENCE and self.maze_ambience_file
                    and self.maze_ambience_data):
                # The freed pipeline goes back to the maze ambience.
                self._arm_maze_repeat(conn, self.maze_ambience_data)
                return conn.play_url(self._maze_audio_url(self.maze_ambience_data),
                                     volume=self._bed_volume(self.maze_ambience_data))
            return conn.stop(announcement=False)
        if command == 'start_maze_ambience':
            if not NODE_GLOBAL_MAZE_AMBIENCE:
                # Browser/VLC clients still get the maze bed. The ESP node's
                # single media stream stays clear for low-latency cue playback.
                logger.debug(f"Node audio [{conn.room}]: maze ambience skipped on node")
                return None
            if conn.bed_active:
                logger.debug(f"Node audio [{conn.room}]: maze ambience deferred — "
                             "the room's own background owns the pipeline")
                return None
            self._arm_maze_repeat(conn, data)
            return conn.play_url(self._maze_audio_url(data),
                                 volume=self._bed_volume(data))
        if command == 'stop_maze_ambience':
            if conn.bed_active:
                return None  # the pipeline is playing the room's bed, not maze ambience
            self._cancel_repeat(conn)
            return conn.stop(announcement=False)
        if command == 'audio_stop':
            return conn.stop(announcement=True)
        logger.debug(f"Node audio: no mapping for WS command '{command}'")
        return None

    def reconcile_maze_ambience_on_nodes(self):
        """Hand the current maze bed to nodes that should be playing it but
        aren't, using the same sync_started_at_s offset. Two cases:

        * no native API client — the node was offline during the original
          start; the dispatch itself reconnects it.
        * connected but the media pipeline reports IDLE mid-window — the play
          command that started the bed can 'succeed' while the stream later
          dies (a server restart kills the HTTP fetch, 2026-08-17), and only
          the device's own pushed state shows the silence.

        Already-playing nodes are never restarted."""
        if (not NODE_GLOBAL_MAZE_AMBIENCE or not self.maze_ambience_file
                or not self.maze_ambience_data):
            return False
        dispatched = False
        for conn in self.rooms.values():
            if conn.bed_active:
                continue
            stalled = conn.client is not None and self._maze_bed_stalled(conn)
            if conn.client is not None and not stalled:
                continue
            coro = self._command_coro(conn, 'start_maze_ambience',
                                      dict(self.maze_ambience_data))
            if coro is None:
                continue
            if stalled:
                logger.info(f"Node audio [{conn.room}]: maze bed stalled — "
                            f"pipeline idle "
                            f"{time.monotonic() - conn.media_state_at:.0f}s "
                            f"mid-window; re-dispatching")
            task = asyncio.create_task(coro)
            self._tasks.add(task)
            task.add_done_callback(self._tasks.discard)
            dispatched = True
        return dispatched

    def _maze_bed_stalled(self, conn):
        """A connected node sitting IDLE past the grace period while the maze
        bed's window is still comfortably open. media_state None (no state
        received / subscription unavailable) is treated as fine — better a
        missed retry than restarting a bed that is audibly playing."""
        if conn.media_state != MEDIA_IDLE or not conn.media_state_at:
            return False
        now = time.monotonic()
        if now - conn.media_state_at < STALL_GRACE_S:
            return False
        data = self.maze_ambience_data or {}
        try:
            started = float(data.get('sync_started_at_s'))
            play_for = float(data.get('play_for_s') or 0)
        except (TypeError, ValueError):
            return True
        if play_for and now - started > play_for - ROTATION_SLOP_S:
            return False
        return True

    def _cancel_repeat(self, conn):
        task = self._repeat_tasks.pop(conn, None)
        if task is not None:
            task.cancel()

    def _cancel_repeats(self):
        for conn in list(self._repeat_tasks):
            self._cancel_repeat(conn)

    def _arm_maze_repeat(self, conn, data):
        self._cancel_repeat(conn)
        if not data.get('loop'):
            return
        if not self._node_loop(data):
            return
        try:
            duration_s = float(self._node_duration(data) or 0)
            play_for_s = float(data.get('play_for_s') or 0)
        except (TypeError, ValueError):
            return
        if duration_s <= 0 or play_for_s <= duration_s:
            return
        task = asyncio.create_task(self._maze_repeat_loop(conn, dict(data)))
        self._repeat_tasks[conn] = task
        task.add_done_callback(lambda done, c=conn: self._drop_repeat(c, done))

    def _drop_repeat(self, conn, task):
        if self._repeat_tasks.get(conn) is task:
            self._repeat_tasks.pop(conn, None)

    async def _maze_repeat_loop(self, conn, data):
        file_name = data.get('file_name')
        volume = self._bed_volume(data)
        deadline = time.monotonic() + float(data['play_for_s'])
        delay = max(1.0, float(self._node_duration(data)) + 0.25)
        try:
            while True:
                await asyncio.sleep(delay)
                if self.maze_ambience_file != file_name or conn.bed_active:
                    return
                if time.monotonic() >= deadline:
                    return
                await conn.play_url(self._maze_audio_url(data), volume=volume)
        except asyncio.CancelledError:
            raise
        except Exception as e:
            logger.error(f"Node audio [{conn.room}] repeat for {file_name} failed: {e}",
                         exc_info=True)
