#!/usr/bin/env bash
# Builds firmware/orb/secrets.h from sim/esphome/secrets.yaml so the orb joins
# the same Wi-Fi as the room nodes. Server host defaults to the bench dev box.
set -eu
cd "$(dirname "$0")"
SECRETS=../../sim/esphome/secrets.yaml
[ -f "$SECRETS" ] || { echo "missing $SECRETS"; exit 1; }
val() { grep -E "^$1:" "$SECRETS" | sed -E 's/^[^:]+: *"?([^"]*)"?.*/\1/'; }
SSID=$(val wifi_ssid)
PASS=$(val wifi_password)
HOST=${ORB_SERVER_HOST:-192.168.253.184}
cat > secrets.h <<EOF
// generated by gen_secrets.sh from sim/esphome/secrets.yaml — do not commit
#pragma once
#define WIFI_SSID "$SSID"
#define WIFI_PASSWORD "$PASS"
#define SERVER_HOST "$HOST"
#define SERVER_PORT 5000
#define OTA_PASSWORD "$PASS"
EOF
echo "secrets.h written (ssid=$SSID host=$HOST)"
