#!/usr/bin/env bash
# Builds firmware/orb/secrets.h from sim/esphome/secrets.yaml so the orb joins
# the same Wi-Fi as the room nodes (LOHP-ESP — wiring-guides/maze-network.md).
# Server host defaults to the server Pi's RUT DHCP reservation; for a bench
# server on the dev box: ORB_SERVER_HOST=<dev box's LOHP-ESP address> ./gen_secrets.sh
set -eu
cd "$(dirname "$0")"
SECRETS=../../sim/esphome/secrets.yaml
[ -f "$SECRETS" ] || { echo "missing $SECRETS"; exit 1; }
val() { grep -E "^$1:" "$SECRETS" | sed -E 's/^[^:]+: *"?([^"]*)"?.*/\1/'; }
SSID=$(val wifi_ssid)
PASS=$(val wifi_password)
HOST=${ORB_SERVER_HOST:-192.168.252.231}
cat > secrets.h <<EOF
// generated by gen_secrets.sh from sim/esphome/secrets.yaml — do not commit
#pragma once
#define WIFI_SSID "$SSID"
#define WIFI_PASSWORD "$PASS"
#define SERVER_HOST "$HOST"
#define SERVER_PORT 5000
#define OTA_PASSWORD "$PASS"
EOF
echo "secrets.h written (ssid=$SSID host=$HOST)"
