#!/usr/bin/env python3
"""Generate per-node firmware audio: converted cue files + the ESPHome package.

Reads node_audio_config.json (which rooms have audio nodes and which effects
each embeds) and audio_config.json (effect -> mp3s + volume), then for every
node:

  1. converts each effect mp3 -> audio/cues/<cue_id>.wav
     (22.05kHz mono s16 — the announcement-pipeline format in
     packages/audio_s3.yaml — with the effect's per-effect VOLUME BAKED IN,
     since the node's media_player volume is shared with the music bed)
  2. writes audio/cues-<node>.yaml: the media_player `files:` list plus the
     `play_cue` api-action dispatch the server calls (node_audio_manager.py
     sends cue ids produced by the same cue_id() imported below)

Include the generated package in the node's yaml alongside audio_s3.yaml.
Outputs are machine-local (absolute paths) and gitignored — rerun after
editing node_audio_config.json, audio_config.json, or the mp3s:

    sim/esphome/make_node_audio.py
"""
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO))
from node_audio_manager import cue_id  # noqa: E402 — single source of cue ids

CUES_DIR = HERE / 'audio' / 'cues'
# Keep total embedded audio well under the app partition headroom
# (8MB flash - dual OTA slots - ~1.5MB firmware).
NODE_BUDGET_BYTES = 2_000_000

DISPATCH_IF = """\
    - if:
        condition:
          lambda: 'return cue == "{cue}";'
        then:
          - media_player.speaker.play_on_device_media_file:
              media_file: cue_{cue}
              announcement: true
"""


def load(path):
    with open(path) as f:
        return json.load(f)


def convert(src, dest, volume):
    subprocess.run(
        ['ffmpeg', '-y', '-loglevel', 'error', '-i', str(src),
         '-ac', '1', '-ar', '22050', '-sample_fmt', 's16',
         '-af', f'volume={volume}', str(dest)],
        check=True)


def node_cues(node_cfg, effects_cfg):
    """-> {cue: (src_path, volume)} for one node, validating as it goes."""
    cues = {}
    for effect in node_cfg.get('effects', []):
        if effect not in effects_cfg:
            sys.exit(f"ERROR: effect '{effect}' not in audio_config.json")
        entry = effects_cfg[effect]
        files = entry.get('audio_files', [])
        if not files:
            print(f"  note: effect '{effect}' has no audio files — skipped")
        for fname in files:
            src = REPO / 'audio_files' / fname
            if not src.exists():
                sys.exit(f"ERROR: {src} missing (effect '{effect}')")
            volume = entry.get('volume', 0.7)
            cue = cue_id(fname)
            if cue in cues and cues[cue] != (src, volume):
                print(f"  WARN: {fname} embedded by two effects with different "
                      f"volumes — keeping the louder")
                volume = max(volume, cues[cue][1])
            cues[cue] = (src, volume)
    return cues


def main():
    node_cfg_all = load(REPO / 'node_audio_config.json')
    effects_cfg = load(REPO / 'audio_config.json')['effects']
    CUES_DIR.mkdir(parents=True, exist_ok=True)

    for room, node_cfg in node_cfg_all.get('rooms', {}).items():
        node = node_cfg.get('node') or room.lower().replace(' ', '-')
        print(f"{node} ({room}):")
        cues = node_cues(node_cfg, effects_cfg)

        total = 0
        files_yaml, dispatch_yaml = [], []
        for cue, (src, volume) in sorted(cues.items()):
            dest = CUES_DIR / f'{cue}.wav'
            convert(src, dest, volume)
            total += dest.stat().st_size
            print(f"  {cue}.wav  {dest.stat().st_size//1024}KB  "
                  f"(from {src.name} @ vol {volume})")
            files_yaml.append(f"      - id: cue_{cue}\n        file: {dest}")
            dispatch_yaml.append(DISPATCH_IF.format(cue=cue))

        out = HERE / 'audio' / f'cues-{node}.yaml'
        out.write_text(
            "# AUTO-GENERATED by make_node_audio.py — do not edit, regenerate.\n"
            f"# Node: {node}  Room: {room}  Embedded: {total//1024}KB\n"
            "media_player:\n"
            "  - id: !extend room_audio\n"
            "    files:\n" + "\n".join(files_yaml) + "\n\n"
            "api:\n"
            "  actions:\n"
            "    - action: play_cue\n"
            "      variables:\n"
            "        cue: string\n"
            "      then:\n"
            "        - logger.log:\n"
            "            format: \"play_cue: %s\"\n"
            "            args: ['cue.c_str()']\n"
            + "".join("    " + line + "\n" for block in dispatch_yaml
                      for line in block.splitlines()))
        print(f"  -> {out.relative_to(HERE)}  total {total//1024}KB"
              + (f"  WARN: over the ~{NODE_BUDGET_BYTES//1_000_000}MB budget!"
                 if total > NODE_BUDGET_BYTES else ""))


if __name__ == '__main__':
    main()
