#!/usr/bin/env python3
"""Generate per-room victory-cue flash banks (rooms/victory-<slug>.yaml).

Tim 2026-08-31 (on-playa): victory sounds must be INSTANT, and a bank of
victory sounds in ESP flash IS sanctioned (music stays streamed — beds ride
live_audio.py). This generalizes the Photo Bomb snap exception: each room's
victory pool (the -RightAnswer pool + its named win effects) is embedded as
on-device media files, one API action per cue named `cue_<cue_id>`.

The server needs no manifest: node_audio_manager reads the service list at
connect and calls `cue_<id>` when the picked file is on the box, streaming
as before when it isn't — un-flashed boxes keep working.

Files come from audio_files/cues/<cue_id>.wav — the SAME volume-baked WAVs
make_node_audio.py generates for streaming (rerun it first after pool or
effect_level changes, then this, then rebuild + OTA the room).

Run from sim/esphome:  python3 make_victory_bank.py
Then ensure the room yaml's packages: block has
  victory_bank: !include victory-<slug>.yaml
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, REPO)
from node_audio_manager import cue_id  # noqa: E402  (the id the server dispatches)

# Keep every bank under this: the S3's OTA app slot is 1.8 MB and the base
# room image runs ~1.0-1.1 MB. Cues are kept smallest-first until the budget
# is spent; dropped cues still play via streaming (the server falls back
# per-cue automatically), so a trimmed bank just means the biggest WAVs in
# the pool arrive the old way.
MAX_BANK_KB = 650

# Room -> the effects whose audio pool is that room's victory bank.
ROOM_VICTORY_EFFECTS = {
    'Bike Lock Room': ['BikeLockRoom', 'BikeLockRoom-RightAnswer'],
    'Gate': ['Gate-RightAnswer'],
    'Guy Line Climb': ['GuyLineClimb-RightAnswer'],
    'Porto Room': ['PortoRoom-RightAnswer'],
    'Sparkle Pony Room': ['SparklePonyRoom-RightAnswer'],
    'Photo Bomb Room': ['PhotoBombRoom-RightAnswer'],
    'Monkey Room': ['MonkeyBusiness'],
    'Vertical Moop March': ['VerticalMoopMarch-RightAnswer'],
}

HEADER = """\
# GENERATED by make_victory_bank.py — do not hand-edit.
# {room}: victory cues baked into flash so the win lands the instant it is
# earned (Tim 2026-08-31; generalizes the Photo Bomb snap exception).
# The server calls the cue_<id> api action when the box carries the cue and
# streams the WAV as before when it doesn't. Source pools: {effects}.
"""


def _slug(name):
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')


def main():
    cfg = json.load(open(os.path.join(REPO, 'audio_config.json')))
    effects = cfg.get('effects', {})
    total = 0
    for room, effect_names in ROOM_VICTORY_EFFECTS.items():
        cues = {}
        for effect_name in effect_names:
            entry = effects.get(effect_name)
            if not isinstance(entry, dict):
                print(f"!! {room}: effect {effect_name} not in audio_config — skipped")
                continue
            for f in entry.get('audio_files') or []:
                cid = cue_id(f)
                wav = os.path.join(REPO, 'audio_files', 'cues', f"{cid}.wav")
                if not os.path.exists(wav):
                    print(f"!! {room}: no baked cue {cid}.wav for {f} "
                          f"(rerun make_node_audio.py) — skipped")
                    continue
                cues[cid] = os.path.getsize(wav)
        if not cues:
            continue
        budget = MAX_BANK_KB * 1024
        kept, spent = {}, 0
        for cid in sorted(cues, key=cues.get):
            if spent + cues[cid] > budget:
                print(f"   {room}: {cid} ({cues[cid] // 1024} KB) over the "
                      f"{MAX_BANK_KB} KB budget — stays streamed")
                continue
            kept[cid] = cues[cid]
            spent += cues[cid]
        cues = kept
        out = [HEADER.format(room=room, effects=', '.join(effect_names))]
        out.append("media_player:\n  - id: !extend room_audio\n    files:")
        for cid in sorted(cues):
            out.append(f"      - id: vic_{cid}\n"
                       f"        file: ../../../audio_files/cues/{cid}.wav")
        out.append("\napi:\n  actions:")
        for cid in sorted(cues):
            out.append(f"    - action: cue_{cid}\n"
                       f"      then:\n"
                       f"        - media_player.speaker.play_on_device_media_file:\n"
                       f"            id: room_audio\n"
                       f"            media_file: vic_{cid}\n"
                       f"            announcement: true")
        path = os.path.join(HERE, 'rooms', 'victory', f"victory-{_slug(room)}.yaml")
        with open(path, 'w') as fh:
            fh.write('\n'.join(out) + '\n')
        size_kb = sum(cues.values()) // 1024
        total += size_kb
        flag = '  <-- LARGE, check OTA partition headroom' if size_kb > 1024 else ''
        print(f"{room:24s} {len(cues):2d} cues {size_kb:5d} KB -> {os.path.relpath(path, HERE)}{flag}")
    print(f"total embedded audio: {total} KB across rooms")


if __name__ == '__main__':
    main()
